# Generated by Django 4.1.7 on 2023-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500, verbose_name='Banner Headline')),
                ('image', models.ImageField(upload_to='', verbose_name='Banner Image')),
                ('top_text', models.CharField(max_length=500, verbose_name='Top text')),
                ('bottom_text', models.CharField(max_length=500, verbose_name='Bottom text')),
                ('optional_text', models.CharField(max_length=500, verbose_name='Optional text')),
            ],
        ),
    ]
