# Generated by Django 4.1.7 on 2023-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('TOP_BANNER', 'Top Banner'), ('MIDDLE_LEFT', 'Middle Left Banner'), ('MIDDLE_RIGHT', 'Middle Right Banner'), ('BOTTOM_BANNER', 'Bottom Banner')], default='TOP_BANNER', max_length=50, verbose_name='Banner Type'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='banner',
            name='redirect_url',
            field=models.URLField(blank=True, null=True, verbose_name='Redirected URL'),
        ),
    ]
