# Generated by Django 4.1.7 on 2023-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_banner_type_banner_is_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('banner_type', 'TOP_BANNER'), ('is_active', True), _connector='OR'), fields=('banner_type',), name='unique_active_banner'),
        ),
    ]
