# Generated by Django 4.1.7 on 2023-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_banner_unique_active_banner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='banner',
            name='unique_active_banner',
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('banner_type', 'TOP_BANNER'), models.Q(('is_active', True), _negated=True), _connector='OR'), fields=('banner_type', 'is_active'), name='unique_active_banner'),
        ),
    ]
