# Generated by Django 4.1.7 on 2023-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_remove_banner_unique_active_banner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='banner',
            name='unique_active_banner',
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('banner_type__in', ['MIDDLE_LEFT', 'MIDDLE_RIGHT', 'BOTTOM_BANNER']), ('is_active', True)), fields=('banner_type', 'is_active'), name='unique_active_banner'),
        ),
    ]
