# Generated by Django 4.1.7 on 2023-04-02 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='First Letter should be in capital followed by small case letter', regex='^[A-Z]{1}[a-z]*$')], verbose_name='Brand Name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='brand_products', to='products.productbrand', verbose_name='Product Brand'),
        ),
    ]
