# Generated by Django 4.1.7 on 2023-04-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productbrand_product_product_brand'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productdiscount',
            name='valid_discount_range',
        ),
        migrations.AddConstraint(
            model_name='productdiscount',
            constraint=models.CheckConstraint(check=models.Q(('discount_percent__gte', 1), ('discount_percent__lte', 99)), name='valid_discount_range', violation_error_message='Discount range should be within 1 to 99 percent'),
        ),
    ]
