# Generated by Django 4.1.7 on 2023-04-02 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productdiscount_valid_discount_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Inavlid Color Code', regex='^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$')], verbose_name='Color Code'),
        ),
    ]
