# Generated by Django 4.1.7 on 2023-04-03 17:44

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcolor_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_path, verbose_name='Image')),
                ('image_code', models.CharField(max_length=100, verbose_name='Image code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product', verbose_name='Product')),
            ],
            options={
                'unique_together': {('product', 'image_code')},
            },
        ),
    ]
