# Generated by Django 4.1.7 on 2023-04-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
